/**
 * Tests for installed-pack-info.ts — parseInfoName + inferPackTypeFromPaths.
 *
 * Round-trip test: build a tiny SGA via the repo's own buildInfoFile / sga-writer,
 * open it with SgaArchive.open, read the .info entry, and verify parseInfoName
 * extracts the name that was written.
 *
 * These tests are purely in-memory (no filesystem I/O) and run under vitest
 * with the jsdom environment.  The SGA MemFile shim from sga-roundtrip.test.ts
 * is duplicated here so this file is self-contained.
 */

import { describe, it, expect } from 'vitest'
import { parseInfoName, inferPackTypeFromPaths } from '@/lib/installed-pack-info'
import { buildInfoFile } from '@/lib/decal-mod-build'
import { buildSga } from '@/lib/sga-writer'
import { SgaArchive } from '@/lib/sga'

// ─── MemFile shim (mirrors sga-roundtrip.test.ts) ────────────────────────────

class MemFile {
  readonly name: string
  readonly size: number
  private readonly data: Uint8Array

  constructor(data: Uint8Array, name = 'test.sga') {
    this.data = data
    this.name = name
    this.size = data.length
  }

  slice(start: number, end?: number): { arrayBuffer(): Promise<ArrayBuffer> } {
    const sliced = this.data.slice(start, end)
    return { arrayBuffer: () => Promise.resolve(sliced.buffer as ArrayBuffer) }
  }
}

// ─── parseInfoName ────────────────────────────────────────────────────────────

describe('parseInfoName', () => {
  it('extracts a simple quoted name', () => {
    const text = `hidden = false\r\nname = "My Skin Pack"\r\ndescription = "desc"\r\n`
    expect(parseInfoName(text)).toBe('My Skin Pack')
  })

  it('handles LF-only line endings', () => {
    const text = `hidden = false\nname = "German Tigers"\ndescription = ""\n`
    expect(parseInfoName(text)).toBe('German Tigers')
  })

  it('unescapes \\\" inside the name', () => {
    const text = `name = "He said \\"hello\\""\n`
    expect(parseInfoName(text)).toBe('He said "hello"')
  })

  it('unescapes \\\\ inside the name', () => {
    const text = `name = "path\\\\sub"\n`
    expect(parseInfoName(text)).toBe('path\\sub')
  })

  it('returns null when no name line is present', () => {
    const text = `hidden = false\r\ndescription = "no name"\r\n`
    expect(parseInfoName(text)).toBeNull()
  })

  it('returns null for an empty name value', () => {
    const text = `name = ""\n`
    expect(parseInfoName(text)).toBeNull()
  })

  it('handles name with leading/trailing whitespace in value (trims)', () => {
    const text = `name = "  Padded Name  "\n`
    expect(parseInfoName(text)).toBe('Padded Name')
  })
})

// ─── inferPackTypeFromPaths ───────────────────────────────────────────────────

describe('inferPackTypeFromPaths', () => {
  it('detects skin from attrib/skin_pack/ path', () => {
    expect(inferPackTypeFromPaths(['attrib/skin_pack/german/foo.rgd'])).toBe('skin')
  })

  it('detects decal from attrib/vehicle_decal/ path', () => {
    expect(inferPackTypeFromPaths(['attrib/vehicle_decal/my_decal_german.rgd'])).toBe('decal')
  })

  it('detects decal from attrib/decal/ path', () => {
    expect(inferPackTypeFromPaths(['attrib/decal/something.rgd'])).toBe('decal')
  })

  it('detects decal from /badges/ path', () => {
    expect(inferPackTypeFromPaths(['art/armies/german/badges/guid/default_dif.rgt'])).toBe('decal')
  })

  it('detects faceplate from attrib/faceplate/ path', () => {
    expect(inferPackTypeFromPaths(['attrib/faceplate/test.rgd'])).toBe('faceplate')
  })

  it('returns unknown for unrecognised paths', () => {
    expect(inferPackTypeFromPaths(['data/something.bin', 'english/strings.ucs'])).toBe('unknown')
  })

  it('returns unknown for empty array', () => {
    expect(inferPackTypeFromPaths([])).toBe('unknown')
  })

  it('handles backslash-separated paths (Windows style)', () => {
    expect(inferPackTypeFromPaths(['attrib\\skin_pack\\german\\foo.rgd'])).toBe('skin')
  })
})

// ─── Round-trip: buildInfoFile → SGA → SgaArchive.open → parseInfoName ───────

describe('round-trip: buildInfoFile → SGA → parseInfoName', () => {
  /**
   * Build a tiny SGA that contains only the .info file generated by
   * `buildInfoFile` from decal-mod-build.ts (the same writer the app uses
   * when exporting a decal pack). Then open it with SgaArchive and verify
   * parseInfoName recovers the original name.
   */
  it('reads the name written by buildInfoFile back via parseInfoName', async () => {
    const packName = 'Heinz Guderian Decals'
    const guid = 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4'

    // Build the .info bytes the same way the app does it
    const fakeProject = {
      packName,
      packDescription: 'A test decal pack for round-trip verification.',
      packVersion: '1',
      decalSlots: [],
      id: 'test',
      name: packName,
      vehicleCount: 0,
    } as unknown as import('@/lib/decal-pack-project').Coh2DecalPackProject
    const infoBytes = buildInfoFile(fakeProject, guid)

    // Embed the .info in a minimal SGA archive
    const sgaBytes = await buildSga({
      archiveName: guid,
      files: [
        { path: `${guid}.info`, bytes: infoBytes, compress: false },
        // A dummy attrib/vehicle_decal/ path so type inference sees 'decal'
        { path: 'attrib/vehicle_decal/test.rgd', bytes: new Uint8Array(4), compress: false },
      ],
    })

    // Open with SgaArchive and locate the .info entry
    const mem = new MemFile(sgaBytes)
    const archive = await SgaArchive.open(mem as unknown as File)

    const infoEntry = archive.list().find(e => e.path.endsWith('.info'))
    expect(infoEntry).toBeDefined()

    const readBytes = await infoEntry!.read()
    const infoText = new TextDecoder('utf-8').decode(readBytes)

    // Parse name
    const recovered = parseInfoName(infoText)
    expect(recovered).toBe(packName)
  })

  it('recovers name with double-quote in it (escape round-trip)', async () => {
    const packName = 'Pack "Alpha"'
    const guid = 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5'
    const fakeProject = {
      packName,
      packDescription: '',
      packVersion: '1',
      decalSlots: [],
      id: 'test',
      name: packName,
      vehicleCount: 0,
    } as unknown as import('@/lib/decal-pack-project').Coh2DecalPackProject

    const infoBytes = buildInfoFile(fakeProject, guid)

    const sgaBytes = await buildSga({
      archiveName: guid,
      files: [{ path: `${guid}.info`, bytes: infoBytes, compress: false }],
    })

    const mem = new MemFile(sgaBytes)
    const archive = await SgaArchive.open(mem as unknown as File)
    const infoEntry = archive.list().find(e => e.path.endsWith('.info'))
    expect(infoEntry).toBeDefined()

    const readBytes = await infoEntry!.read()
    const infoText = new TextDecoder('utf-8').decode(readBytes)
    const recovered = parseInfoName(infoText)

    expect(recovered).toBe(packName)
  })

  it('skin pack .info written by rewriteInfo (via mod-export) round-trips', async () => {
    // mod-export.ts uses rewriteInfo which has the same key=value format.
    // We test by manually creating the same format and verifying parseInfoName.
    const packName = 'SS3 Summer Heavy'
    // Build raw .info content matching the rewriteInfo output
    const rawInfo = `hidden = false\r\nname = "${packName}"\r\ndescription = "Stock German camo"\r\ndependencies = \r\n{\r\n}\r\n`
    const infoBytes = new TextEncoder().encode(rawInfo)

    const sgaBytes = await buildSga({
      archiveName: 'test',
      files: [
        { path: '935a02ef44344ea29108b57b9cb7b9f5.info', bytes: infoBytes, compress: false },
        { path: 'attrib/skin_pack/german/foo.rgd', bytes: new Uint8Array(4), compress: false },
      ],
    })

    const mem = new MemFile(sgaBytes)
    const archive = await SgaArchive.open(mem as unknown as File)
    const infoEntry = archive.list().find(e => e.path.endsWith('.info'))
    expect(infoEntry).toBeDefined()

    const readBytes = await infoEntry!.read()
    const infoText = new TextDecoder('utf-8').decode(readBytes)
    const recovered = parseInfoName(infoText)

    expect(recovered).toBe(packName)
  })
})
